// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python_agent.proto

package com.popcorn.agent.core.adapter.python.grpc;

/**
 * <pre>
 * 数据处理请求
 * </pre>
 *
 * Protobuf type {@code com.agent.adapter.python.DataProcessRequest}
 */
public final class DataProcessRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.agent.adapter.python.DataProcessRequest)
    DataProcessRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DataProcessRequest.newBuilder() to construct.
  private DataProcessRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DataProcessRequest() {
    data_ = "";
    processType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DataProcessRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DataProcessRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            data_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            processType_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.popcorn.agent.core.adapter.python.grpc.PythonAgentProto.internal_static_com_agent_adapter_python_DataProcessRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.popcorn.agent.core.adapter.python.grpc.PythonAgentProto.internal_static_com_agent_adapter_python_DataProcessRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest.class, com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest.Builder.class);
  }

  public static final int DATA_FIELD_NUMBER = 1;
  private volatile java.lang.Object data_;
  /**
   * <pre>
   * 原始数据（JSON格式）
   * </pre>
   *
   * <code>string data = 1;</code>
   * @return The data.
   */
  @java.lang.Override
  public java.lang.String getData() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      data_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 原始数据（JSON格式）
   * </pre>
   *
   * <code>string data = 1;</code>
   * @return The bytes for data.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDataBytes() {
    java.lang.Object ref = data_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      data_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROCESS_TYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object processType_;
  /**
   * <pre>
   * 处理类型：clean-清洗，convert-转换
   * </pre>
   *
   * <code>string process_type = 2;</code>
   * @return The processType.
   */
  @java.lang.Override
  public java.lang.String getProcessType() {
    java.lang.Object ref = processType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      processType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 处理类型：clean-清洗，convert-转换
   * </pre>
   *
   * <code>string process_type = 2;</code>
   * @return The bytes for processType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProcessTypeBytes() {
    java.lang.Object ref = processType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      processType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, data_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(processType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, processType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, data_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(processType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, processType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest)) {
      return super.equals(obj);
    }
    com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest other = (com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest) obj;

    if (!getData()
        .equals(other.getData())) return false;
    if (!getProcessType()
        .equals(other.getProcessType())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DATA_FIELD_NUMBER;
    hash = (53 * hash) + getData().hashCode();
    hash = (37 * hash) + PROCESS_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getProcessType().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 数据处理请求
   * </pre>
   *
   * Protobuf type {@code com.agent.adapter.python.DataProcessRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.agent.adapter.python.DataProcessRequest)
      com.popcorn.agent.core.adapter.python.grpc.DataProcessRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.popcorn.agent.core.adapter.python.grpc.PythonAgentProto.internal_static_com_agent_adapter_python_DataProcessRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.popcorn.agent.core.adapter.python.grpc.PythonAgentProto.internal_static_com_agent_adapter_python_DataProcessRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest.class, com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest.Builder.class);
    }

    // Construct using com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      data_ = "";

      processType_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.popcorn.agent.core.adapter.python.grpc.PythonAgentProto.internal_static_com_agent_adapter_python_DataProcessRequest_descriptor;
    }

    @java.lang.Override
    public com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest getDefaultInstanceForType() {
      return com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest build() {
      com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest buildPartial() {
      com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest result = new com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest(this);
      result.data_ = data_;
      result.processType_ = processType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest) {
        return mergeFrom((com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest other) {
      if (other == com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest.getDefaultInstance()) return this;
      if (!other.getData().isEmpty()) {
        data_ = other.data_;
        onChanged();
      }
      if (!other.getProcessType().isEmpty()) {
        processType_ = other.processType_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object data_ = "";
    /**
     * <pre>
     * 原始数据（JSON格式）
     * </pre>
     *
     * <code>string data = 1;</code>
     * @return The data.
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 原始数据（JSON格式）
     * </pre>
     *
     * <code>string data = 1;</code>
     * @return The bytes for data.
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 原始数据（JSON格式）
     * </pre>
     *
     * <code>string data = 1;</code>
     * @param value The data to set.
     * @return This builder for chaining.
     */
    public Builder setData(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      data_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原始数据（JSON格式）
     * </pre>
     *
     * <code>string data = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearData() {
      
      data_ = getDefaultInstance().getData();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 原始数据（JSON格式）
     * </pre>
     *
     * <code>string data = 1;</code>
     * @param value The bytes for data to set.
     * @return This builder for chaining.
     */
    public Builder setDataBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      data_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object processType_ = "";
    /**
     * <pre>
     * 处理类型：clean-清洗，convert-转换
     * </pre>
     *
     * <code>string process_type = 2;</code>
     * @return The processType.
     */
    public java.lang.String getProcessType() {
      java.lang.Object ref = processType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        processType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 处理类型：clean-清洗，convert-转换
     * </pre>
     *
     * <code>string process_type = 2;</code>
     * @return The bytes for processType.
     */
    public com.google.protobuf.ByteString
        getProcessTypeBytes() {
      java.lang.Object ref = processType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 处理类型：clean-清洗，convert-转换
     * </pre>
     *
     * <code>string process_type = 2;</code>
     * @param value The processType to set.
     * @return This builder for chaining.
     */
    public Builder setProcessType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      processType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 处理类型：clean-清洗，convert-转换
     * </pre>
     *
     * <code>string process_type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearProcessType() {
      
      processType_ = getDefaultInstance().getProcessType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 处理类型：clean-清洗，convert-转换
     * </pre>
     *
     * <code>string process_type = 2;</code>
     * @param value The bytes for processType to set.
     * @return This builder for chaining.
     */
    public Builder setProcessTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      processType_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.agent.adapter.python.DataProcessRequest)
  }

  // @@protoc_insertion_point(class_scope:com.agent.adapter.python.DataProcessRequest)
  private static final com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest();
  }

  public static com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DataProcessRequest>
      PARSER = new com.google.protobuf.AbstractParser<DataProcessRequest>() {
    @java.lang.Override
    public DataProcessRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DataProcessRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DataProcessRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataProcessRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.popcorn.agent.core.adapter.python.grpc.DataProcessRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

