// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python_agent.proto

package com.popcorn.agent.core.adapter.python.grpc;

public interface DataProcessResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.agent.adapter.python.DataProcessResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <pre>
   * 处理后数据（JSON格式）
   * </pre>
   *
   * <code>string processed_data = 2;</code>
   * @return The processedData.
   */
  java.lang.String getProcessedData();
  /**
   * <pre>
   * 处理后数据（JSON格式）
   * </pre>
   *
   * <code>string processed_data = 2;</code>
   * @return The bytes for processedData.
   */
  com.google.protobuf.ByteString
      getProcessedDataBytes();

  /**
   * <code>string error_msg = 3;</code>
   * @return The errorMsg.
   */
  java.lang.String getErrorMsg();
  /**
   * <code>string error_msg = 3;</code>
   * @return The bytes for errorMsg.
   */
  com.google.protobuf.ByteString
      getErrorMsgBytes();

  /**
   * <code>int64 cost_time = 4;</code>
   * @return The costTime.
   */
  long getCostTime();
}
