// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python_agent.proto

package com.popcorn.agent.core.adapter.python.grpc;

/**
 * <pre>
 * LLM推理响应
 * </pre>
 * <p>
 * Protobuf type {@code com.agent.adapter.python.LlmInferResponse}
 */
public final class LlmInferResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.agent.adapter.python.LlmInferResponse)
        LlmInferResponseOrBuilder {
    public static final int SUCCESS_FIELD_NUMBER = 1;
    public static final int RESULT_FIELD_NUMBER = 2;
    public static final int ERROR_MSG_FIELD_NUMBER = 3;
    private static final long serialVersionUID = 0L;
    // @@protoc_insertion_point(class_scope:com.agent.adapter.python.LlmInferResponse)
    private static final com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse DEFAULT_INSTANCE;
    private static final com.google.protobuf.Parser<LlmInferResponse>
            PARSER = new com.google.protobuf.AbstractParser<LlmInferResponse>() {
        @java.lang.Override
        public LlmInferResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new LlmInferResponse(input, extensionRegistry);
        }
    };

    static {
        DEFAULT_INSTANCE = new com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse();
    }

    private boolean success_;
    private volatile java.lang.Object result_;
    private volatile java.lang.Object errorMsg_;
    private byte memoizedIsInitialized = -1;

    // Use LlmInferResponse.newBuilder() to construct.
    private LlmInferResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private LlmInferResponse() {
        result_ = "";
        errorMsg_ = "";
    }

    private LlmInferResponse(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 8: {

                        success_ = input.readBool();
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        result_ = s;
                        break;
                    }
                    case 26: {
                        java.lang.String s = input.readStringRequireUtf8();

                        errorMsg_ = s;
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return com.popcorn.agent.core.adapter.python.grpc.PythonAgentProto.internal_static_com_agent_adapter_python_LlmInferResponse_descriptor;
    }

    public static com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public static com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    public static com.google.protobuf.Parser<LlmInferResponse> parser() {
        return PARSER;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new LlmInferResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return com.popcorn.agent.core.adapter.python.grpc.PythonAgentProto.internal_static_com_agent_adapter_python_LlmInferResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse.class, com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse.Builder.class);
    }

    /**
     * <pre>
     * 调用是否成功
     * </pre>
     *
     * <code>bool success = 1;</code>
     *
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
        return success_;
    }

    /**
     * <pre>
     * 推理结果
     * </pre>
     *
     * <code>string result = 2;</code>
     *
     * @return The result.
     */
    @java.lang.Override
    public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            result_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 推理结果
     * </pre>
     *
     * <code>string result = 2;</code>
     *
     * @return The bytes for result.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            result_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * <pre>
     * 错误信息（失败时非空）
     * </pre>
     *
     * <code>string error_msg = 3;</code>
     *
     * @return The errorMsg.
     */
    @java.lang.Override
    public java.lang.String getErrorMsg() {
        java.lang.Object ref = errorMsg_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            errorMsg_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * 错误信息（失败时非空）
     * </pre>
     *
     * <code>string error_msg = 3;</code>
     *
     * @return The bytes for errorMsg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getErrorMsgBytes() {
        java.lang.Object ref = errorMsg_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            errorMsg_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (success_ != false) {
            output.writeBool(1, success_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(result_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, result_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMsg_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errorMsg_);
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (success_ != false) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBoolSize(1, success_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(result_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, result_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(errorMsg_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errorMsg_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse)) {
            return super.equals(obj);
        }
        com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse other = (com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse) obj;

        if (getSuccess()
                != other.getSuccess()) return false;
        if (!getResult()
                .equals(other.getResult())) return false;
        if (!getErrorMsg()
                .equals(other.getErrorMsg())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getSuccess());
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + getResult().hashCode();
        hash = (37 * hash) + ERROR_MSG_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMsg().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LlmInferResponse> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

    /**
     * <pre>
     * LLM推理响应
     * </pre>
     * <p>
     * Protobuf type {@code com.agent.adapter.python.LlmInferResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.agent.adapter.python.LlmInferResponse)
            com.popcorn.agent.core.adapter.python.grpc.LlmInferResponseOrBuilder {
        private boolean success_;
        private java.lang.Object result_ = "";
        private java.lang.Object errorMsg_ = "";

        // Construct using com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return com.popcorn.agent.core.adapter.python.grpc.PythonAgentProto.internal_static_com_agent_adapter_python_LlmInferResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return com.popcorn.agent.core.adapter.python.grpc.PythonAgentProto.internal_static_com_agent_adapter_python_LlmInferResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse.class, com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse.Builder.class);
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            success_ = false;

            result_ = "";

            errorMsg_ = "";

            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return com.popcorn.agent.core.adapter.python.grpc.PythonAgentProto.internal_static_com_agent_adapter_python_LlmInferResponse_descriptor;
        }

        @java.lang.Override
        public com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse getDefaultInstanceForType() {
            return com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse.getDefaultInstance();
        }

        @java.lang.Override
        public com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse build() {
            com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse buildPartial() {
            com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse result = new com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse(this);
            result.success_ = success_;
            result.result_ = result_;
            result.errorMsg_ = errorMsg_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse) {
                return mergeFrom((com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse other) {
            if (other == com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse.getDefaultInstance()) return this;
            if (other.getSuccess() != false) {
                setSuccess(other.getSuccess());
            }
            if (!other.getResult().isEmpty()) {
                result_ = other.result_;
                onChanged();
            }
            if (!other.getErrorMsg().isEmpty()) {
                errorMsg_ = other.errorMsg_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.popcorn.agent.core.adapter.python.grpc.LlmInferResponse) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        /**
         * <pre>
         * 调用是否成功
         * </pre>
         *
         * <code>bool success = 1;</code>
         *
         * @return The success.
         */
        @java.lang.Override
        public boolean getSuccess() {
            return success_;
        }

        /**
         * <pre>
         * 调用是否成功
         * </pre>
         *
         * <code>bool success = 1;</code>
         *
         * @param value The success to set.
         * @return This builder for chaining.
         */
        public Builder setSuccess(boolean value) {

            success_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 调用是否成功
         * </pre>
         *
         * <code>bool success = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearSuccess() {

            success_ = false;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 推理结果
         * </pre>
         *
         * <code>string result = 2;</code>
         *
         * @return The result.
         */
        public java.lang.String getResult() {
            java.lang.Object ref = result_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                result_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * 推理结果
         * </pre>
         *
         * <code>string result = 2;</code>
         *
         * @param value The result to set.
         * @return This builder for chaining.
         */
        public Builder setResult(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            result_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 推理结果
         * </pre>
         *
         * <code>string result = 2;</code>
         *
         * @return The bytes for result.
         */
        public com.google.protobuf.ByteString
        getResultBytes() {
            java.lang.Object ref = result_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                result_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 推理结果
         * </pre>
         *
         * <code>string result = 2;</code>
         *
         * @param value The bytes for result to set.
         * @return This builder for chaining.
         */
        public Builder setResultBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            result_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 推理结果
         * </pre>
         *
         * <code>string result = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearResult() {

            result_ = getDefaultInstance().getResult();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 错误信息（失败时非空）
         * </pre>
         *
         * <code>string error_msg = 3;</code>
         *
         * @return The errorMsg.
         */
        public java.lang.String getErrorMsg() {
            java.lang.Object ref = errorMsg_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                errorMsg_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * 错误信息（失败时非空）
         * </pre>
         *
         * <code>string error_msg = 3;</code>
         *
         * @param value The errorMsg to set.
         * @return This builder for chaining.
         */
        public Builder setErrorMsg(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            errorMsg_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 错误信息（失败时非空）
         * </pre>
         *
         * <code>string error_msg = 3;</code>
         *
         * @return The bytes for errorMsg.
         */
        public com.google.protobuf.ByteString
        getErrorMsgBytes() {
            java.lang.Object ref = errorMsg_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                errorMsg_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * 错误信息（失败时非空）
         * </pre>
         *
         * <code>string error_msg = 3;</code>
         *
         * @param value The bytes for errorMsg to set.
         * @return This builder for chaining.
         */
        public Builder setErrorMsgBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            errorMsg_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * 错误信息（失败时非空）
         * </pre>
         *
         * <code>string error_msg = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearErrorMsg() {

            errorMsg_ = getDefaultInstance().getErrorMsg();
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.agent.adapter.python.LlmInferResponse)
    }

}

